### PR TITLE
Initialize PageTreeNode when reading a PDF - Fix for #33

### PR DESCRIPTION
**Pull request by moritzgloeckl**
Hi,

this is my proposed fix for #33 - It seems to be working for me but definitely needs more testing. 

How it works:

If we're given a Hash from parsing an existing PDF and the Types are correct -> set the values.

Feedback? Ideas?

Thanks

### CODE REVIEW

**Comment by mcelicalderon** [comment]
I have tested this works. I'm also unable to parse any PDF with https://github.com/gdelugre/origami/commit/cdc155777fb2faeb16e64ffd2677f5e2b3328d57 or current master https://github.com/gdelugre/origami/commit/98ea557af7aa9e926aac564bf89e6e0ead4a1a5e

**Comment by moritzgloeckl** [comment]
@gdelugre Any updates on this?

**Comment by meganemura** [comment]
@gdelugre Would you please review this?

**Comment by gdelugre** [comment]
Sorry for having taken so long to fix this.

It should be fixed by 9282cae738d7e33ef06dc05b976b4a2e2571440d.

**Comment by moritzgloeckl** [comment]
@gdelugre Thanks! Your solution is way more elegant. I'm closing this.

**Pull request closed without merging**
